name: "Ubuntu 20.04 + clang"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CMAKE_BUILD_TYPE: Debug
  CC: clang
  CXX: clang++

jobs:

  configure_build_test:
    name: "Install, configure, build and test"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: sudo apt-get update
    - name: Install GTK
      run: sudo apt-get install libgtk-3-dev
    - name: Configure
      run: CC=${{env.CC}} CXX=${{env.CXX}} cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE:STRING=${{env.CMAKE_BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.CMAKE_BUILD_TYPE}}
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.CMAKE_BUILD_TYPE}}
